#!/usr/bin/env bash
# Script that configures the server so that:
# - localhost resolves to 127.0.0.2
# - facebook.com resolves to 8.8.8.8

printf "127.0.0.2 localhost\n8.8.8.8 facebook.com\n" | sudo tee /etc/hosts > /dev/null
