#!/usr/bin/env bash
# Script that configures the server so that:
# - localhost resolves to 127.0.0.2
# - facebook.com resolves to 8.8.8.8
sudo sed -i 's/127.0.0.1\s\+localhost/127.0.0.2\tlocalhost/' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
