#!/usr/bin/env bash
# Script that configures the server so that:
# - localhost resolves to 127.0.0.2
# - facebook.com resolves to 8.8.8.8

sudo bash -c 'echo -e "127.0.0.2 localhost\n8.8.8.8 facebook.com" > /etc/hosts'
